#!/bin/bash
#download from a list of multiple URLs in a txt file
while read line; do yt-dlp $line -P ~/yt-dlp; done < list_of_urls.txt
#~/yt-dlp is the absolute path to a directory selected to be the destination of the downloaded videos.
